name: Update & Publish (README.md)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/scripts/repo.yml"
  workflow_dispatch:
  repository_dispatch:
    types: [ readme-template-updated ]


jobs:
  call-central:
    uses: Academic-Codex/academic-codex.github.io/.github/workflows/build-readme.yml@main
    with:
      repo_cfg_path: ".github/scripts/repo.yml"
    secrets: inherit